MODEL_POOL = [
        "Llama-3-8B-Instruct",
        "Llama-3-70B-Instruct",
        "Llama-2-7b-chat-hf",
        "Llama-2-13b-chat-hf",
        "qwen2-7B-Instruct",
        "qwen2-72B-Instruct",
        "Mistral-7B-Instruct",
        "Qwen1.5-7B-Chat",
        "Qwen-7B-Chat",
        "OLMo-7B-0724-Instruct-hf",
        "OLMo-2-1124-7B-Instruct",
        "Baichuan2-7B-Chat"
    ]


DATASET_POOL = [
    "mgsm",
    "math",
    "commonsenseqa",
    "theoremqa",
    "gsm8k_train_1",
    "gsm8k_train_2",
    "gsm8k_train_3",
    "gsm8k_train_4",
    "gsm8k_train_5",
    "gsm8k_train_6",
    "gsm8k_train_7",
    "gsm8k_train_8",
    "gsm8k_train_9",
    "gsm8k_train_10",
    "gsm8k_test_1",
    "gsm8k_test_2",
    "gsm8k_test_3",
    "gsm8k_test_4",
    "gsm8k_test_5",
    "gsm8k_test_6",
    "gsm8k_test_7",
    "gsm8k_test_8",
    "gsm8k_test_9",
    "gsm8k_test_10",
    "gsm8k_test_11",
    "gsm8k_test_12",
    "gsm8k_test_13",
    "gsm8k_test_14",
    "gsm8k_test_15",
    "gsm8k_test_16",
    "gsm8k_test_17",
    "gsm8k_test_18",
    "gsm8k_test_19",
    "gsm8k_test_20",
    "svamp_train_1",
    "svamp_train_2",
    "svamp_train_3",
    "svamp_train_4",
    "svamp_train_5",
    "svamp_train_6",
    "svamp_train_7",
    "svamp_train_8",
    "svamp_train_9",
    "svamp_train_10",
    "svamp_test_1",
    "svamp_test_2",
    "svamp_test_3",
    "svamp_test_4",
    "svamp_test_5",
    "svamp_test_6",
    "svamp_test_7",
    "svamp_test_8",
    "svamp_test_9",
    "svamp_test_10",
    "svamp_test_11",
    "svamp_test_12",
    "svamp_test_13",
    "svamp_test_14",
    "svamp_test_15",
    "svamp_test_16",
    "svamp_test_17",
    "svamp_test_18",
    "svamp_test_19",
    "svamp_test_20",
   	"gsmsymbolic_test_1",
    "gsmsymbolic_test_2",
    "gsmsymbolic_test_3",
    "gsmsymbolic_test_4",
    "gsmsymbolic_test_5",
    "gsmsymbolic_test_6",
    "gsmsymbolic_test_7",
    "gsmsymbolic_test_8",
    "gsmsymbolic_test_9",
    "gsmsymbolic_test_10",
    "gsmsymbolic_test_11",
    "gsmsymbolic_test_12",
    "gsmsymbolic_test_13",
    "gsmsymbolic_test_14",
    "gsmsymbolic_test_15",
    "gsmsymbolic_test_16",
    "gsmsymbolic_test_17",
    "gsmsymbolic_test_18",
    "gsmsymbolic_test_19",
    "gsmsymbolic_test_20",
    "commonsenseqa_train_1",
    "commonsenseqa_train_2",
    "commonsenseqa_train_3",
    "commonsenseqa_train_4",
    "commonsenseqa_train_5",
    "commonsenseqa_train_6",
    "commonsenseqa_train_7",
    "commonsenseqa_train_8",
    "commonsenseqa_train_9",
    "commonsenseqa_train_10",
    "commonsenseqa_test_1",
    "commonsenseqa_test_2",
    "commonsenseqa_test_3",
    "commonsenseqa_test_4",
    "commonsenseqa_test_5",
    "commonsenseqa_test_6",
    "commonsenseqa_test_7",
    "commonsenseqa_test_8",
    "commonsenseqa_test_9",
    "commonsenseqa_test_10",
    "commonsenseqa_test_11",
    "commonsenseqa_test_12",
    "commonsenseqa_test_13",
    "commonsenseqa_test_14",
    "commonsenseqa_test_15",
    "commonsenseqa_test_16",
    "commonsenseqa_test_17",
    "commonsenseqa_test_18",
    "commonsenseqa_test_19",
    "commonsenseqa_test_20",
    "mbpp_train_1",
    "mbpp_train_2",
    "mbpp_train_3",
    "mbpp_train_4",
    "mbpp_train_5",
    "mbpp_train_6",
    "mbpp_train_7",
    "mbpp_train_8",
    "mbpp_train_9",
    "mbpp_train_10",
    "mbpp_train_11",
    "mbpp_train_12",
    "mbpp_train_13",
    "mbpp_train_14",
    "mbpp_train_15",
    "mbpp_train_16",
    "mbpp_train_17",
    "mbpp_train_18",
    "mbpp_train_19",
    "mbpp_train_20",
    "mbpp_train_21",
    "mbpp_train_22",
    "mbpp_train_23",
    "mbpp_train_24",
    "mbpp_train_25",
    "mbpp_train_26",
    "mbpp_train_27",
    "mbpp_train_28",
    "mbpp_train_29",
    "mbpp_train_30",
    "mbpp_train_31",
    "mbpp_train_32",
    "mbpp_train_33",
    "mbpp_train_34",
    "mbpp_train_35",
    "mbpp_train_36",
    "mbpp_train_37",
    "mbpp_train_38",
    "mbpp_train_39",
    "mbpp_train_40",
    "mbpp_train_41",
    "mbpp_train_42",
    "mbpp_train_43",
    "mbpp_train_44",
    "mbpp_train_45",
    "mbpp_train_46",
    "mbpp_train_47",
    "mbpp_train_48",
    "mbpp_train_49",
    "mbpp_train_50",
    "mbpp_test_1",
    "mbpp_test_2",
    "mbpp_test_3",
    "mbpp_test_4",
    "mbpp_test_5",
    "mbpp_test_6",
    "mbpp_test_7",
    "mbpp_test_8",
    "mbpp_test_9",
    "mbpp_test_10",
    "mbpp_test_11",
    "mbpp_test_12",
    "mbpp_test_13",
    "mbpp_test_14",
    "mbpp_test_15",
    "mbpp_test_16",
    "mbpp_test_17",
    "mbpp_test_18",
    "mbpp_test_19",
    "mbpp_test_20",

]

LANGUAGE_MAPPING = {
    "mgsm": ["en", "bn", "de", "es", "fr", "ja", "ru", "sw", "te", "th", "zh"],
    "gsm8k_train_1": ["en"],
    "gsm8k_train_2": ["en"],
    "gsm8k_train_3": ["en"],
    "gsm8k_train_4": ["en"],
    "gsm8k_train_5": ["en"],
    "gsm8k_train_6": ["en"],
    "gsm8k_train_7": ["en"],
    "gsm8k_train_8": ["en"],
    "gsm8k_train_9": ["en"],
    "gsm8k_train_10": ["en"],
    "gsm8k_test_1": ["en"],
    "gsm8k_test_2": ["en"],
    "gsm8k_test_3": ["en"],
    "gsm8k_test_4": ["en"],
    "gsm8k_test_5": ["en"],
    "gsm8k_test_6": ["en"],
    "gsm8k_test_7": ["en"],
    "gsm8k_test_8": ["en"],
    "gsm8k_test_9": ["en"],
    "gsm8k_test_10": ["en"],
    "gsm8k_test_11": ["en"],
    "gsm8k_test_12": ["en"],
    "gsm8k_test_13": ["en"],
    "gsm8k_test_14": ["en"],
    "gsm8k_test_15": ["en"],
    "gsm8k_test_16": ["en"],
    "gsm8k_test_17": ["en"],
    "gsm8k_test_18": ["en"],
    "gsm8k_test_19": ["en"],
    "gsm8k_test_20": ["en"],
    "svamp_train_1": ["en"],
    "svamp_train_2": ["en"],
    "svamp_train_3": ["en"],
    "svamp_train_4": ["en"],
    "svamp_train_5": ["en"],
    "svamp_train_6": ["en"],
    "svamp_train_7": ["en"],
    "svamp_train_8": ["en"],
    "svamp_train_9": ["en"],
    "svamp_train_10": ["en"],
    "svamp_test_1": ["en"],
    "svamp_test_2": ["en"],
    "svamp_test_3": ["en"],
    "svamp_test_4": ["en"],
    "svamp_test_5": ["en"],
    "svamp_test_6": ["en"],
    "svamp_test_7": ["en"],
    "svamp_test_8": ["en"],
    "svamp_test_9": ["en"],
    "svamp_test_10": ["en"],
    "svamp_test_11": ["en"],
    "svamp_test_12": ["en"],
    "svamp_test_13": ["en"],
    "svamp_test_14": ["en"],
    "svamp_test_15": ["en"],
    "svamp_test_16": ["en"],
    "svamp_test_17": ["en"],
    "svamp_test_18": ["en"],
    "svamp_test_19": ["en"],
    "svamp_test_20": ["en"],
    "gsmsymbolic_test_1": ["en"],
    "gsmsymbolic_test_2": ["en"],
    "gsmsymbolic_test_3": ["en"],
    "gsmsymbolic_test_4": ["en"],
    "gsmsymbolic_test_5": ["en"],
    "gsmsymbolic_test_6": ["en"],
    "gsmsymbolic_test_7": ["en"],
    "gsmsymbolic_test_8": ["en"],
    "gsmsymbolic_test_9": ["en"],
    "gsmsymbolic_test_10": ["en"],
    "gsmsymbolic_test_11": ["en"],
    "gsmsymbolic_test_12": ["en"],
    "gsmsymbolic_test_13": ["en"],
    "gsmsymbolic_test_14": ["en"],
    "gsmsymbolic_test_15": ["en"],
    "gsmsymbolic_test_16": ["en"],
    "gsmsymbolic_test_17": ["en"],
    "gsmsymbolic_test_18": ["en"],
    "gsmsymbolic_test_19": ["en"],
    "gsmsymbolic_test_20": ["en"],
    "commonsenseqa_train_1": ["en"],
    "commonsenseqa_train_2": ["en"],
    "commonsenseqa_train_3": ["en"],
    "commonsenseqa_train_4": ["en"],
    "commonsenseqa_train_5": ["en"],
    "commonsenseqa_train_6": ["en"],
    "commonsenseqa_train_7": ["en"],
    "commonsenseqa_train_8": ["en"],
    "commonsenseqa_train_9": ["en"],
    "commonsenseqa_train_10": ["en"],
    "commonsenseqa_test_1": ["en"],
    "commonsenseqa_test_2": ["en"],
    "commonsenseqa_test_3": ["en"],
    "commonsenseqa_test_4": ["en"],
    "commonsenseqa_test_5": ["en"],
    "commonsenseqa_test_6": ["en"],
    "commonsenseqa_test_7": ["en"],
    "commonsenseqa_test_8": ["en"],
    "commonsenseqa_test_9": ["en"],
    "commonsenseqa_test_10": ["en"],
    "commonsenseqa_test_11": ["en"],
    "commonsenseqa_test_12": ["en"],
    "commonsenseqa_test_13": ["en"],
    "commonsenseqa_test_14": ["en"],
    "commonsenseqa_test_15": ["en"],
    "commonsenseqa_test_16": ["en"],
    "commonsenseqa_test_17": ["en"],
    "commonsenseqa_test_18": ["en"],
    "commonsenseqa_test_19": ["en"],
    "commonsenseqa_test_20": ["en"],
    "mbpp_train_1": ["en"],
    "mbpp_train_2": ["en"],
    "mbpp_train_3": ["en"],
    "mbpp_train_4": ["en"],
    "mbpp_train_5": ["en"],
    "mbpp_train_6": ["en"],
    "mbpp_train_7": ["en"],
    "mbpp_train_8": ["en"],
    "mbpp_train_9": ["en"],
    "mbpp_train_10": ["en"],
    "mbpp_train_11": ["en"],
    "mbpp_train_12": ["en"],
    "mbpp_train_13": ["en"],
    "mbpp_train_14": ["en"],
    "mbpp_train_15": ["en"],
    "mbpp_train_16": ["en"],
    "mbpp_train_17": ["en"],
    "mbpp_train_18": ["en"],
    "mbpp_train_19": ["en"],
    "mbpp_train_20": ["en"],
    "mbpp_train_21": ["en"],
    "mbpp_train_22": ["en"],
    "mbpp_train_23": ["en"],
    "mbpp_train_24": ["en"],
    "mbpp_train_25": ["en"],
    "mbpp_train_26": ["en"],
    "mbpp_train_27": ["en"],
    "mbpp_train_28": ["en"],
    "mbpp_train_29": ["en"],
    "mbpp_train_30": ["en"],
    "mbpp_train_31": ["en"],
    "mbpp_train_32": ["en"],
    "mbpp_train_33": ["en"],
    "mbpp_train_34": ["en"],
    "mbpp_train_35": ["en"],
    "mbpp_train_36": ["en"],
    "mbpp_train_37": ["en"],
    "mbpp_train_38": ["en"],
    "mbpp_train_39": ["en"],
    "mbpp_train_40": ["en"],
    "mbpp_train_41": ["en"],
    "mbpp_train_42": ["en"],
    "mbpp_train_43": ["en"],
    "mbpp_train_44": ["en"],
    "mbpp_train_45": ["en"],
    "mbpp_train_46": ["en"],
    "mbpp_train_47": ["en"],
    "mbpp_train_48": ["en"],
    "mbpp_train_49": ["en"],
    "mbpp_train_50": ["en"],
    "mbpp_test_1": ["en"],
    "mbpp_test_2": ["en"],
    "mbpp_test_3": ["en"],
    "mbpp_test_4": ["en"],
    "mbpp_test_5": ["en"],
    "mbpp_test_6": ["en"],
    "mbpp_test_7": ["en"],
    "mbpp_test_8": ["en"],
    "mbpp_test_9": ["en"],
    "mbpp_test_10": ["en"],
    "mbpp_test_11": ["en"],
    "mbpp_test_12": ["en"],
    "mbpp_test_13": ["en"],
    "mbpp_test_14": ["en"],
    "mbpp_test_15": ["en"],
    "mbpp_test_16": ["en"],
    "mbpp_test_17": ["en"],
    "mbpp_test_18": ["en"],
    "mbpp_test_19": ["en"],
    "mbpp_test_20": ["en"],
}